### ISSUE TITLE
use asyncio/aiohttp or gevent + wsgi?

### ISSUE THREAD

**Issue by iamybj** [KeepSafe/aiohttp#1289]
use asyncio/aiohttp or gevent + wsgi?

**Comment by fafhrd91** [comment]
with gevent you can use existing code, for aiohttp you have to write code that uses asyncio and aiohttp

**Comment by asvetlov** [comment]
@iamybj are you asking for the best solution?
As the aiohttp maintainer I vote on aiohttp.
But it's very opinion based answer.
Even stackoverflow will block your question for the same reason.
