### ISSUE TITLE
I suggest shutdown asnycio, aiohttp projets after 1 day researching

### ISSUE THREAD

**Issue by iamybj** [KeepSafe/aiohttp#1291]
aysnc api is good but not practical, it is antihuman.
human enslave computers, not computers enslave human.
asnycio and aio http run at the wrong way.
corutiune of gevent, gorutine of go, they are the correct way.
if all of you have time, you can contribute gevent and other similar projects.

**Comment by fafhrd91** [comment]
useless

**Comment by iamybj** [comment]
you are useless.

**Comment by asvetlov** [comment]
@iamybj please be polite.
If you don't like a project -- just don't use it.
If you prefer Go -- what are you doing here?
Please left comments on projects which are Go-based web servers.
The same for gevent.
